### ISSUE TITLE
Seems that the Mina App 1.0.0-beta.4 does not work with the latest Ledger firmware.

### ISSUE THREAD

**Issue by Hispano4946** [jspada/ledger-app-mina#10]
It seems that the Mina App (1.0.0-beta.4) is not compatible with the new firmware version (2.0.0) of the Ledger Nano S device.
When I try to create a Mina address from Ubuntu 18.04 with this command:

**_./mina_ledger_wallet get-address 0
Get address for account 0 (path 44'/12586'/0'/0/0)
Continue? (y/N) y_**

Produce this error:

**_Generating address (please confirm on Ledger device)... Failed to communicate with ledger device (error = 25873)_**

The device also crashes (crashes and freezes image3) when I run the Mina app (1.0.0-beta.4) on the Ledger (the Ledger disconnects from the PC). I have to unplug it and plug it back into usb to get it working again.

The device works perfectly from the application ledger-live-desktop-2.26.1-linux-x86_64.AppImage

![error](https://user-images.githubusercontent.com/29433041/118264409-f0fc1800-b4b7-11eb-8fa4-f4b2ba51b679.png)

![IMG_20210512_140754](https://user-images.githubusercontent.com/29433041/118264826-97481d80-b4b8-11eb-9d39-99ffe644bb06.jpg)
![IMG_20210514_132331](https://user-images.githubusercontent.com/29433041/118264829-97e0b400-b4b8-11eb-9c34-d55d7ec52631.jpg)

**Comment by jspada** [comment]
Correct- this is why we have released version `1.0.2`
