### ISSUE TITLE
Mina app unresponsive on Ledger Nano S - Most recent Firmware version (1.6.1)

### ISSUE THREAD

**Issue by humapathy** [jspada/ledger-app-mina#11]
Hi I wanted to indicated that the issue is still there, wherein the Mina app goes to unresponsive mode at 'Open application' screen in the Ledger Nano S.  I do have the latest Firmware version of Ledger (1.6.1) please help

**Comment by jspada** [comment]
The most recent Nano S firmware is `2.0.0` - please upgrade.
