### ISSUE TITLE
Ledger Nano S stuck on "Open Application" after upgrading

### ISSUE THREAD

**Issue by omrikiei** [jspada/ledger-app-mina#12]
Hi - thank you for this great app
I had v1.0.0 and upgraded to the latest stable 1.02 - the ledger device is stuck on "Open application" (after approving the not genuine app signature)

I've tried uninstalling and re-installing and it yields the same behaviour.
Uninstalling and re-installing v1.0.0 works so it seems that there's a problem with v1.0.2 on the latest ledger nano S
Nano S version is 1.6.1

**Comment by muffetman** [comment]
I can confirm the exact same problem on v1.0.1 and v1.0.2 with the Nano S running v1.6.1.

**Comment by raspstar** [comment]
Please try to update the Ledger to FW 2.0.0

**Comment by muffetman** [comment]
Oops, that was it. Ledger Manager was telling me my Nano was up to date, but only because I was running an older version of Ledger Live. Updating Ledger Live followed by an update to firmware 2.0 resolved the issue, although though I have the same problem as issue #18
