### ISSUE TITLE
Status of approval by Ledger?

### ISSUE THREAD

**Issue by rsmets** [jspada/ledger-app-mina#19]
I am curious what the status is in regard to becoming an official Ledger app? How can I track its progress? 

I understand I can subscribe to Ledger updates to get the announcement of its support, however, I am curious what means of communication will happen on this open-source side?

Thanks for all your efforts on the project!

**Comment by jspada** [comment]
Thanks!  This is completely up to Ledger, who have not committed to any timeline.

You could track progress by watching this repo https://github.com/LedgerHQ/app-mina

**Comment by coolcodemy** [comment]
can you push those ledger dev to approve it faster? really need this on my X.. 😢
