### ISSUE TITLE
 Failed to communicate with ledger device (error = 28160)

### ISSUE THREAD

**Issue by edsphinx** [jspada/ledger-app-mina#2]
Using Ledger App Mina 1.0.0-beta.3, when I try to generate key pair running:
 mina_ledger_wallet get-address 42

I got the error:
Generating address (please confirm on Ledger device)... Failed to communicate with ledger device (error = 28160)

On macOS 10.15.7

I was able to generate successfully with Ledger App Mina 1.0.0-beta.2

**Comment by jspada** [comment]
Con you confirm your ledger is plugged into USB, unlocked, Mina app is loaded and no other Ledger devices are plugged into any other USB ports?

**Comment by edsphinx** [comment]
> Con you confirm your ledger is plugged into USB, unlocked, Mina app is loaded and no other Ledger devices are plugged into any other USB ports?

I can confirm all that, because with the beta2 I was able to connect without issues and generate the key pair successfully, I having this issue with beta3 only, and tried several times, verify everything before opening this issue, I even removed previous installations of the beta2 attempts already.

**Comment by jspada** [comment]
Could you please do the following
1. Report your ledgerblue version
2. Report your Ledger Nano S firmware version
3. Run beta3 with `--verbose` flag and paste output here
4. Test again with `beta2` and confirm that it still works?
