### ISSUE TITLE
(Un)install scripts missing shebang

### ISSUE THREAD

**Issue by dduan** [jspada/ledger-app-mina#20]
The scripts included in releases for installing and uninstalling the Ledger app doesn't work as an executable in some environment (macOS + fish shell, for example) because it doesn't have a shebang. When running as-is, users will see the following output:

```
❯ ./install.sh
Failed to execute process './install.sh'. Reason:
exec: Exec format error
The file './install.sh' is marked as an executable but could not be run by the operating system.
```

The solution is to add a shebang at beginning of `install.sh`, and `uninstall.sh`:

```
#!/bin/sh

...
```

**Comment by jspada** [comment]
Fixed by `1f2acf7bbdcad7f1480c31bde039ba7d75da0c08`
