### ISSUE TITLE
Wallet created a year ago Ledger+webwallet, now trying to access but cant get to the right address.

### ISSUE THREAD

**Issue by Metatronovich** [jspada/ledger-app-mina#23]
Crated my address about a year ago using ledger nano (when mina app demanded the developer switch to be on) with clorio web wallet.

trying to access the wallet now using deviation path 0,1,42,99 (according to their docs) - gives me the wrong address.

I can see the right public address on the mina explorer (bookmarked it before), but I cant access it using the web wallet.

anyone know what could be the problem?

thanks

**Comment by merlinana** [comment]
@Metatronovich Talk to Ledger Support on the [Ledger Live support](https://explore-ledger.online/) so that your issue can be looked into.

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by jspada** [comment]
Hi there -- The last changes to `crypto.c` in this repo were long ago on (Jul 6, 2021), predating your indicated address creation date.  Regarding changes between `1.0.6` and `1.0.8`, you will need to speak with Ledger.  This repo stopped at version `1.0.2` after which the source code was taken over and maintained by Ledger.  The official repo is now https://github.com/LedgerHQ/app-mina

In case it's helpful, note that the derivation path quoted above (`0,1,42,99`) does not match what Mina used for its mainnet launch (and what is currently used), which is `44,12586,<account_num>`.  Perhaps try using this derivation path and trying different account numbers sequentially and getting in touch with Ledger.
