### ISSUE TITLE
Invalid status 6484

### ISSUE THREAD

**Issue by iamnathanwindsor** [jspada/ledger-app-mina#3]
I am using a Ledger Nano S. I have no other ledgers on the computer.

How do I fix this?

I installed Ledger App Mina 1.0.0-beta.3, and when I try to run the .install/.sh I get:

"Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/ledgerblue/loadApp.py", line 204, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/usr/local/lib/python3.9/site-packages/ledgerblue/deployed.py", line 91, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/usr/local/lib/python3.9/site-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6484 (Are you using the correct targetId?)"

**Comment by jspada** [comment]
Hi - Could you please tell me
1. Your host operating system and version
2. Your ledgerblue version
3. Your Ledger Nano S firmware version

**Comment by tloriato** [comment]
Same situation:
- macOS 11.3.1

**Ledger Nano X:**
- Secure Element 1.2.4.5
- Microcontroller 2.10
- Bootloader 1.4



```
Please unlock your Ledger device and exit any apps (press any key to continue)
Generated random root public key : b'0<censored>ce'
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/ledgerblue/loadApp.py", line 204, in <module>
    secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
  File "/usr/local/lib/python3.9/site-packages/ledgerblue/deployed.py", line 91, in getDeployedSecretV2
    dongle.exchange(apdu)
  File "/usr/local/lib/python3.9/site-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6484 (Are you using the correct targetId?)
```

**Comment by jspada** [comment]
> Same situation:
> 
>     * macOS 11.3.1
> 
> 
> **Ledger Nano X:**
> 
>     * Secure Element 1.2.4.5
> 
>     * Microcontroller 2.10
> 
>     * Bootloader 1.4
> 
> 
> ```
> Please unlock your Ledger device and exit any apps (press any key to continue)
> Generated random root public key : b'0<censored>ce'
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.9/site-packages/ledgerblue/loadApp.py", line 204, in <module>
>     secret = getDeployedSecretV2(dongle, bytearray.fromhex(args.rootPrivateKey), args.targetId)
>   File "/usr/local/lib/python3.9/site-packages/ledgerblue/deployed.py", line 91, in getDeployedSecretV2
>     dongle.exchange(apdu)
>   File "/usr/local/lib/python3.9/site-packages/ledgerblue/comm.py", line 145, in exchange
>     raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
> ledgerblue.commException.CommException: Exception : Invalid status 6484 (Are you using the correct targetId?)
> ```

Nano X is currently not supported.  This is because Nano X is not able to load non-approved apps.  Once `ledger-app-mina` is approved by Ledger then it will be possible.

**Comment by tloriato** [comment]
Ah, @jspada ! Sorry, the commit message tricked me!

**Comment by jspada** [comment]
Ah, no worries - it should "just work" once it's approved. 👍🏼

**Comment by jspada** [comment]
Nano X has been supported for while now, as ledger-app-mina has been approved by Ledger and is available through Ledger Live Manager.
