### ISSUE TITLE
Ledger Nano S unresponsive upon loading Mina App

### ISSUE THREAD

**Issue by yourbuddyconner** [jspada/ledger-app-mina#4]
When launching the Mina Ledger app on a fresh Nano S, the device hangs on the "Open non-genuine app?" dialogue after pressing submit. The prompts on the ledger are subtly different than in the docs, probably due to my firmware being outdated `1.5.1`. 

I am updating to the latest firmware and will update if things work out. Recommend listing compatible ledger firmware versions.

**Comment by yourbuddyconner** [comment]
Update: was the firmware version, if anyone else encounters this, updating your ledger should do the trick.

**Comment by jspada** [comment]
Thanks for reporting this!  Updated documentation.

**Comment by Marco-Esquandolas** [comment]
I have a similar issue... I have installed the latest Mina Ledger app on a brand new Nano S with firmware 2.0 but when I try to open the Mina app on the ledger the device freezes. It warns me that the app is not authentic then I select it anyway and it just freezes. If I am connected and Ledger Live is open, I am immediately disconnected.

Anybody got a clue?

Also.. I am at this step in the process: 

To derive a keypair and obtain the associated Mina address, open the Mina app on your Ledger device and then on your terminal use mina_ledger_wallet command.

For example, to get the Mina address corresponding to hardware wallet account 42 (BIP44 account 44'/12586'/42'/0/0) you would issue the following command.:

./mina_ledger_wallet get-address 42

My question is How do I know what number my hardware wallet is? The statement above is not very explanatory!

Thanks for the help!
