### ISSUE TITLE
firmware displayed on device does not match

### ISSUE THREAD

**Issue by nicolasochem** [jspada/ledger-app-mina#5]
I followed installation instructions, but I was stumped for a while because the app hash displayed on the script output did not match the one displayed on the ledger device.

I realized I was on firmware 1.6.1 and the install script has 1.6.0 hardcoded under `--targetVersion`.

After changing it manually to 1.6.1, the firmware match.

It's probably worth documenting, until the app becomes official.

**Comment by jspada** [comment]
The install instructions say to use the SHA256 checksum of the download instead of the app hash, etc.  See Section "Launch the installation script" of https://docs.minaprotocol.com/en/advanced/ledger-app-mina
