### ISSUE TITLE
Can't delegate/send transaction

### ISSUE THREAD

**Issue by ArtemBernatskyy** [jspada/ledger-app-mina#6]
Mac OS 10.13.6
Ledger Nano S (version of mina app `1.0.0`)
Version of app: `ledgerblue==0.1.35`
I'm not running mina node on Mac OS, I 'm running it on dedicated server

Trying to run via this command `mina_ledger_wallet send-payment my_cold_wallet_id my_cold_wallet_aka_ledger_wallet my_hot_wallet 2.71821`
Where `my_cold_wallet_id` will be 0 for example

But I get this error

```
Getting network identifier... Error: HTTPConnectionPool(host='localhost', port=3087):
Max retries exceeded with url: /network/list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c3f5b00>:
Failed to establish a new connection: [Errno 61] Connection refused'))
```

PS but I can execute `mina_ledger_wallet test-transaction 42 B62qnzbXmRNo9q32n4SNu2mpB8e7FYYLH8NmaX6oFCBYjjQ8SbD7uzV`

**Comment by argonau7** [comment]
Not running on VPS, are you?

**Comment by ArtemBernatskyy** [comment]
@argonau7 
I'm running `my_hot_wallet` on Mac OS (in order to connect to ledger wallet)
and running mina node on a dedicated server

**Comment by jspada** [comment]
It's giving you a network connection error because `mina_ledger_wallet` needs to communicate with `mina-rosetta` and you don't have that running.  Once `mina-rosetta` is packaged with Mina then you will not have this issue.
