### ISSUE TITLE
Test transaction failing

### ISSUE THREAD

**Issue by iAmMichaelConnor** [jspada/ledger-app-mina#7]
I just tried to validate a keypair (which is definitely a valid keypair*) and it failed with `Transaction was invalid. Some transactions failed to verify`.

Command: `mina_ledger_wallet test-transaction 42 <B62...> | mina advanced validate-transaction`

*The key pair is definitely valid, because I've previously successfully sent a transaction to the mainnet from this address, using the ledger app.

To test, I tried to generate a new key pair (at a different account slot 43), and validation on that new key pair also failed.

I'm using the latest 1.0.0-beta.4-0-gb... version of the app.

Ubuntu 20.04.2 LTS
Ledger nano S firmware version:
- Secure Element 1.6.1
- Microcontroller 1.12
- Bootloader 0.11

**Comment by jspada** [comment]
For the `test-transaction` operation, which was developed to be used on the testnets, you need to specify `--network mainnet` if you want to test against the current `mina` build that is on `mainnet`

**Comment by jspada** [comment]
👍🏼
