### ISSUE TITLE
App version is always 1.0.0

### ISSUE THREAD

**Issue by nerdvibe** [jspada/ledger-app-mina#8]
Hey there,

I already discussed this with @jspada a while ago, but I'm now opening an issue so it doesn't get forgotten at the next release.

1.0.0-beta-3 and 1.0.0-beta-4 are not compatible with each other, in particular during signature. I got multiple reports of users from https://clor.io that they can't sign transactions. It turns out that the issue is that they were on 1.0.0-beta-3 instead of beta 4.

For the user is impossible to understand on which version they are running if in both cases because the returned version is just 1.0.0.

Can we have with the next releases improved versioning? 🙏

**Comment by jspada** [comment]
Thanks for opening this.

The Ledger device only supports a 3 components version number and all of the releases so far have been pre-releases.

We will try to make the first version approved by ledger 1.0.1, unless Ledger requires us to start at 1.0.0 for some reason.

**Comment by jspada** [comment]
Not any more :-)

**Comment by nerdvibe** [comment]
Thank you 😻
