### ISSUE TITLE
Ledger not found on Linux on Windows WSL

### ISSUE THREAD

**Issue by argonau7** [jspada/ledger-app-mina#9]
In order to check the ledger address, as requested by the Foundation, we need the ledger to be connected to a node. Alas, my node is on VPS so I tried to create one on Windows using the instructions https://minawiki.com/index.php?title=Mina_on_Windows. Everything worked fine except when trying to connect to the Ledger, the error I am getting is "Failed to communicate with ledger device (error = 28416)". Is there a way to make the Ubuntu WSL "see" the plugged in Ledger?

**Comment by jspada** [comment]
There is an `--offline` mode for `mina_leger_wallet` so you do not need to run a full node.

Could you please report your
1. Ledgerblue version
2. Ledger Nano S firmware version

**Comment by argonau7** [comment]
Hello. 

Firmare: 1.6.1. 
Ledgerblue, most recent one as per website so I assume ledgerblue 0.1.35

**Comment by jspada** [comment]
Please try upgrading the firmware and make sure you do not have LedgerLive or any other Ledger application running in the background?
